<?php

namespace Byteland\BytelandBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends EntityRepository
{
    /**
     * Find by date and restaurant
     *
     * @param Restaurant $restaurant
     * @param \DateTime $date.
     */
    public function findByDate(Restaurant $restaurant, $date)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a from BytelandBundle:Availability a WHERE a.date=:a_date AND a.restaurant=:restaurant'
            )
            ->setParameter('a_date', $date)
            ->setParameter('restaurant', $restaurant)
            ->getArrayResult();
    }
}
