<?php

namespace Byteland\BytelandBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
	/**
	 * Find by date and restaurant
	 *
	 * @param Restaurant $restaurant
	 * @param \DateTime $date.
	 */
	public function findByDate(Restaurant $restaurant, $date)
	{
    	return $this->getEntityManager()
    	->createQuery(
    		'SELECT b from BytelandBundle:Booking b WHERE b.date=:b_date AND b.restaurant=:restaurant'
    		)
    	->setParameter('b_date', $date)
    	->setParameter('restaurant', $restaurant)
    	->getArrayResult();
    }
}
