byteland_person:
    resource: "@BytelandBundle/Resources/config/routing/person.yml"
    prefix:   /person

byteland_homepage:
    path:     /schema
    defaults: { _controller: BytelandBundle:Default:index }
