byteland_booking:
    resource: "@BytelandBundle/Resources/config/routing/booking.yml"
    prefix:   /booking

byteland_availability:
    resource: "@BytelandBundle/Resources/config/routing/availability.yml"
    prefix:   /availability

byteland_restaurant:
    resource: "@BytelandBundle/Resources/config/routing/restaurant.yml"
    prefix:   /restaurant

byteland_person:
    resource: "@BytelandBundle/Resources/config/routing/person.yml"
    prefix:   /person

byteland_homepage:
    path:     /schema
    defaults: { _controller: BytelandBundle:Default:index }
