services:
    person.repository:
        class: Byteland\BytelandDomain\Persistence\Doctrine\DoctrinePersonRepository
    restaurant.repository:
        class: Byteland\BytelandDomain\Persistence\Doctrine\DoctrineRestaurantRepository
    booking.repository:
        class: Byteland\BytelandDomain\Persistence\Doctrine\DoctrineBookingRepository
    availabiliti.repository:
        class: Byteland\BytelandDomain\Persistence\Doctrine\DoctrineAvailabilityRepository